### ISSUE TITLE
Overflow(?) Error

### ISSUE THREAD

**Issue by kabuto93** [Medabots/medarot3#166]
[m3_kuwagata_overflow.zip](https://github.com/Medabots/medarot3/files/11162260/m3_kuwagata_overflow.zip)
Just talk to clerk to trigger.

**Comment by VariantXYZ** [comment]
Ah... this is due to "Interior Decorator" being the item in question (18 characters). 

Currently we cap copies into cBUF06 at 17 (16 characters + 1 terminator).

I could just increase it to 19, which seems like our longest part, but realistically, we might just need to shorten this, since it doesn't even fit in the part screen:

![image](https://github.com/Medabots/medarot3/assets/3066132/60206e3b-2b0b-4a15-a802-d88acc2facf8)

**Comment by VariantXYZ** [comment]
This'll just require changing some of the strings, but we can do:

```
Interior Decorator -> Int. Decorator
Blanker Expression -> Blank Expression
Improved Missile -> Imp. Missile (this one actually fits, but I need to change the others, so this makes it consistent)
Bottomless Shovel -> BottomlessShovel (it was just one character off)
Improved Machinegun -> Imp. Machinegun
Crawling In Again -> Crawling In 2 (???)
Improved Ochitsuka -> Imp. Ochitsuka
```
